### ISSUE TITLE
Got an error when running "git lfs pull".

### ISSUE THREAD

**Issue by WangJiuniu** [cetinsamet/attribute-label-embedding#2]
The following description is reported when  running "git lfs pull":
Git LFS: (0 of 15 files) 0 B / 455.62 MB                                                                                                                   
This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/
This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/

Could you please help me to solve this problem if it is possible?

**Comment by cetinsamet** [comment]
Hi,

Yes, it turns out that unfortunately I already filled up my storage capacity. Well, I have just updated README file where you can follow the instructions and reach preprocessed data. 

1 - You can run data/prepareData.ipynb script and let it create APYP/ directory for you.
or
2- You can download data/ directory directly from the GoogleDrive link I've just shared.

Best.
